import { build } from 'esbuild';
import { inject } from 'postject';
import { mkdir, writeFile, readFile, copyFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
if(process.platform!=='win32')throw Error('Compila el EXE desde Windows con Node.js 22 o posterior.');
const root=fileURLToPath(new URL('../',import.meta.url));
const temp=join(root,'.build-temp','windows'),dist=join(root,'dist');
await mkdir(temp,{recursive:true});await mkdir(dist,{recursive:true});
const bundled=join(temp,'streamdeck.cjs'),blob=join(temp,'streamdeck.blob'),exe=join(dist,'StreamDeck-TV.exe');
await build({entryPoints:[join(root,'scripts/windows-entry.js')],outfile:bundled,bundle:true,platform:'node',target:'node22',format:'cjs',define:{'import.meta.url':'"file:///streamdeck/server/app.js"'},logLevel:'warning'});
const assets=Object.fromEntries(['index.html','app.js','style.css','icon.svg','tmdb.svg'].map(name=>['public/'+name,join(root,'public',name)]));
const config=join(temp,'sea.json');
await writeFile(config,JSON.stringify({main:bundled,output:blob,assets,disableExperimentalSEAWarning:true,useSnapshot:false,useCodeCache:false}));
const prepared=spawnSync(process.execPath,['--experimental-sea-config',config],{stdio:'inherit',windowsHide:true});
if(prepared.status!==0)throw Error('Falló la preparación del ejecutable');
await copyFile(process.execPath,exe);
await inject(exe,'NODE_SEA_BLOB',await readFile(blob),{sentinelFuse:'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2'});
await copyFile(join(root,'.env.example'),join(dist,'.env.example'));
const hash=createHash('sha256').update(await readFile(exe)).digest('hex');
await writeFile(join(dist,'SHA256SUMS.txt'),hash+'  StreamDeck-TV.exe\n');
console.log('Generado: '+exe+'\nSin credenciales; configuración privada externa.');
