plugins { id 'com.android.application' }
android {
    namespace 'es.streamdeck.tv'
    compileSdk 35
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    defaultConfig {
        applicationId 'es.streamdeck.tv'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '1.1.0'
    }
    buildTypes { release { minifyEnabled false } }
}
